version: 2
jobs:
  build:
    docker:
      - image: centos:7

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: ls
          command: ls -la

      - run:
          name: yum
          command: yum install ssh git vim

      - run:
          name: Vim version
          command: vim --version

      - run:
          name: Greeting
          command: echo Hello, world.
